/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011-2015 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Application
    magneticFoam

Description
    Solver for the magnetic field generated by permanent magnets.

    A Poisson's equation for the magnetic scalar potential psi is solved
    from which the magnetic field intensity H and magnetic flux density B
    are obtained.  The paramagnetic particle force field (H dot grad(H))
    is optionally available.

\*---------------------------------------------------------------------------*/

#include "fvCFD.H"
#include "OSspecific.H"
#include "magnet.H"
#include "electromagneticConstants.H"
#include "simpleControl.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{

    #include "setRootCase.H"
    #include "createTime.H"
    #include "createMesh.H"

    #include "createFields.H"

    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
    fileName file("savedResults");

    OFstream of(file);

    of<<"\"the time\"" << "\"the rms(root-mean-square) current\"" << '\t' << "\"the ratating speed(rpm)\"" << '\t'
      << "\"the U phase inductance\"" << '\t' << "\"the V phase inductance\"" << '\t'
      << "\"the W phase inductance\"" << '\t' << "\"the torque\"" << '\t' 
      << "\"the voltage\"" << nl;

    while (runTime.loop())
    {
        
        #include "magneticDefine.H"

        #include "calcEMF.H"
       
        Info<< "calculating for time: "<< runTime.value() << endl;

        solve(fvm::laplacian(murf, psi) + fvc::div(murf*Mrf));

        #include "calcBH.H"

        #include "calcInductance.H"
    
        #include "calcTorque.H"

        #include "outputCtrl.H"
    }

    Info<< "\nEnd\n" << endl;
    
    return 0;
}


// ************************************************************************* //
