#define pi 3.1415926

scalar m_num = 8;      //number of magnetic in a sub motor

scalar m_L = 58.5e-3;     //the lenght of magnetic
scalar m_W = 16.5e-3;     //the width of magnetic
scalar m_H = 5e-3;        //the height of magnetic

scalar m_distance = 182e-3;   //the distance from magnetic to origin(0 0 0)

scalar m_theta = pi/4/m_num;    //delta theta between two magnetics

scalar m_z0 = 0;        //magnetic z axis position

scalar m_z1 = m_L;

scalar Mri = 860000;       //Mr of magnetic
